library:
  source-dirs: src
tests:
  ImageProcessing-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ImageProcessing
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- lens
- binary
- bytestring
- base >= 4.7 && < 5
name: ImageProcessing
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/ImageProcessing
license: BSD3
executables:
  ImageProcessing-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ImageProcessing
description: Please see the README on GitHub at <https://github.com/githubuser/ImageProcessing#readme>
